// Sri Ayyappa Crackers - Complete Product Catalog
const CONTACTS = [
  { id: 'gowtham', name: 'Gowtham', phone: '9640499753', displayPhone: '+91 96404 99753', role: 'Main Orders & Support', isDefault: true },
  { id: 'guruswami', name: 'Guruswami', phone: '9573047342', displayPhone: '+91 95730 47342', role: 'Sales & Bulk Booking' }
];

const CATEGORIES = [
  { id: 'all', name: 'All Fireworks', icon: '✨' },
  { id: 'sparklers', name: 'Sparklers (కాకరపువ్వులు)', icon: '☀️' },
  { id: 'ground', name: 'Ground Items (భూచక్రాలు)', icon: '🌀' },
  { id: 'twinkling', name: 'Twinkling & Torches', icon: '🔦' },
  { id: 'sound', name: 'Bombs & Sound Items (బమ్బ్యల్లు)', icon: '💥' },
  { id: 'shots', name: 'Sky Shots & Rockets (రాకెట్లు)', icon: '🚀' },
  { id: 'special-packs', name: 'Family Packs (ఫ్యామిలీ ప్యాక్)', icon: '🎁' }
];

const PRODUCTS = [
  // ------------------------------------------------------------------
  // Sparklers
  // ------------------------------------------------------------------
  {
    id: '7cm-sparklers',
    name: '7cm Sparklers',
    teluguName: 'కాకరపువ్వులు 7 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 20,
    image: 'images/kakarapulu-7cm10-pieces.jpg',
    description: 'Bright golden and silver sparks suitable for kids and quick celebrations.',
    rating: 4.8,
    badge: 'Best Seller'
  },
  {
    id: '7cm-electrical-sparklers',
    name: '7cm Electrical Sparklers',
    teluguName: 'ఎలక్ట్రికల్ స్పార్కిల్స్ 7 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 20,
    image: 'images/7cm-electrical-sparklers.jpg',
    description: 'Battery operated electric sparklers with a steady bright glow, safe for indoor use.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: '15cm-red-colour-sparklers',
    name: '15cm Red Colour Sparklers',
    teluguName: 'ఎరుపు రంగు కాకరపువ్వులు 15 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 70,
    image: 'images/15cm-red-colour-sparklers.jpg',
    description: 'Vibrant dual-color green and red glittering sparks with long burning duration.',
    rating: 4.9,
    badge: 'Popular'
  },
  {
    id: '15cm-green-colour-sparklers',
    name: '15cm Green Colour Sparklers',
    teluguName: 'ఆకుపచ్చ రంగు కాకరపువ్వులు 15 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 70,
    image: 'images/15cm-green-colour-sparklers.jpg',
    description: 'Vibrant dual-color green and red glittering sparks with long burning duration.',
    rating: 4.9,
    badge: 'Popular'
  },
  {
    id: '30cm-electrical-sparklers',
    name: '30cm Electrical Sparklers',
    teluguName: 'ఎలక్ట్రికల్ స్పార్కిల్స్ 30 సెం.మీ',
    pieces: '5 pieces',
    category: 'sparklers',
    price: 70,
    image: 'images/30cm-electrical-sparklers.jpg',
    description: 'Long electric sparklers giving a bright festive glow for a longer duration.',
    rating: 4.7
  },
  // ------------------------------------------------------------------
  // Ground Items
  // ------------------------------------------------------------------
  {
    id: 'chichubudi-big-box',
    name: 'Chichubudi Big Box',
    teluguName: 'చిచ్చుబుడ్లు పెద్ద బాక్స్',
    pieces: '10 pieces',
    category: 'ground',
    price: 300,
    originalPrice: 375,
    discount: '20% OFF',
    image: 'images/chichubudi-big-box.jpg',
    description: 'High-height majestic flower fountain with multi-layered shower of sparks.',
    rating: 5.0,
    badge: 'Grand Flower'
  },
  {
    id: 'chichubudi-medium-box',
    name: 'Chichubudi Medium Box',
    teluguName: 'చిచ్చుబుడ్లు మధ్యమ్ బాక్స్',
    pieces: '10 pieces',
    category: 'ground',
    price: 250,
    originalPrice: 313,
    discount: '20% OFF',
    image: 'images/chichubudi-medium-box.jpg',
    description: 'Medium size chichubudlu flower pots that spin bright colour wheels on the ground.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'chichubudi-small-box',
    name: 'Chichubudi Small Box',
    teluguName: 'చిచ్చుబుడ్లు చిన్న బాక్స్',
    pieces: '10 pieces',
    category: 'ground',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/chichubudi-small-box.jpg',
    description: 'Beautiful golden spray fountain that illuminates your courtyard festive style.',
    rating: 4.9,
    badge: 'Top Pick'
  },
  {
    id: 'bhuchakralu-big-box',
    name: 'Bhuchakralu Big Box',
    teluguName: 'భూచక్రాలు పెద్ద బాక్స్',
    pieces: '10 pieces',
    category: 'ground',
    price: 250,
    originalPrice: 313,
    discount: '20% OFF',
    image: 'images/bhuchakralu-big-box.jpg',
    description: 'High-speed spinning wheel producing a huge ring of dynamic sparks.',
    rating: 4.9,
    badge: 'Popular'
  },
  {
    id: 'bhuchakralu-small',
    name: 'Bhuchakralu Small',
    teluguName: 'భూచక్రాలు చిన్నవి',
    pieces: '10 pieces',
    category: 'ground',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/bhuchakralu-small.jpg',
    description: 'Classic ground chakkar with smooth continuous spin and glittering circle.',
    rating: 4.7
  },
  // ------------------------------------------------------------------
  // Twinkling & Torches
  // ------------------------------------------------------------------
  {
    id: 'chitpataluu',
    name: 'Chitpataluu',
    teluguName: 'చితపటాలు',
    pieces: '10 pieces',
    category: 'twinkling',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/chitpataluu.jpg',
    description: 'Playful crackling sounds with golden micro-sparks on the ground.',
    rating: 4.6
  },
  {
    id: 'venamudal-u',
    name: 'Venamudal(u)',
    teluguName: 'వెన్నముద్దలు',
    pieces: '10 pieces',
    category: 'twinkling',
    price: 40,
    originalPrice: 50,
    discount: '20% OFF',
    image: 'images/venamudal-u.jpg',
    description: 'Smooth glowing ground crackers with soft sound and warm light.',
    rating: 4.5
  },
  {
    id: 'colour-match-box',
    name: 'Colour Match Box',
    teluguName: 'కలర్ మ్యాచ్ బాక్స్',
    pieces: '12 pieces',
    category: 'twinkling',
    price: 20,
    image: 'images/colour-match-box.png',
    description: 'Assorted colour match boxes that light instantly and burn with bright flames.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'pamubilalu',
    name: 'Pamubilalu',
    teluguName: 'పాముబిళ్ళలు',
    pieces: '12 pieces',
    category: 'twinkling',
    price: 20,
    image: 'images/pamubilalu.jpg',
    description: 'Pocket-friendly black snake pellets for fun Diwali games.',
    rating: 4.4
  },
  {
    id: 'threads-tadulu-big',
    name: 'Threads (Tadulu) Big',
    teluguName: 'తాడులు పెద్దవి',
    pieces: '10 pieces',
    category: 'twinkling',
    price: 130,
    originalPrice: 163,
    discount: '20% OFF',
    image: 'images/threads-tadulu-big.png',
    description: 'Long sparkling threads that give a continuous crackling shower of sparks.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'threads-tadulu-small',
    name: 'Threads (Tadulu) Small',
    teluguName: 'తాడులు చిన్నవి',
    pieces: '10 pieces',
    category: 'twinkling',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/threads-tadulu-small.png',
    description: 'Short sparkling threads, handy for children and indoor celebrations.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'pop-pos-nelatapakayalu',
    name: 'Pop Pos (Nelatapakayalu)',
    teluguName: 'పాప్ పాజ్ (నేలటపాకాయలు)',
    pieces: '20 pieces',
    category: 'twinkling',
    price: 10,
    image: 'images/pop-pos-nelatapakayalu.png',
    description: 'Classic pop-pop ground snappers safe and enjoyable for children.',
    rating: 4.7
  },
  {
    id: 'pencils',
    name: 'Pencils',
    teluguName: 'పెన్సిల్స్ మత్తి',
    pieces: '10 pieces',
    category: 'twinkling',
    price: 130,
    originalPrice: 163,
    discount: '20% OFF',
    image: 'images/pencils.jpg',
    description: 'Handheld pencil sticks producing continuous bursts of bright colorful stars.',
    rating: 4.8,
    badge: 'Kids Favourite'
  },
  // ------------------------------------------------------------------
  // Bombs & Sound Items
  // ------------------------------------------------------------------
  {
    id: 'smoke-bombs',
    name: 'Smoke Bombs',
    teluguName: 'స్మోక్ బాంబులు',
    pieces: '20 pieces',
    category: 'sound',
    price: 30,
    image: 'images/smoke-bombs.jpg',
    description: 'Smoke bombs that release thick coloured smoke columns for dramatic effect.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'sematapakayalu-100-pieces',
    name: 'Sematapakayalu 100 Pieces',
    teluguName: 'సీమటపాకాయలు 100 మీస',
    pieces: '100 pieces',
    category: 'sound',
    price: 70,
    image: 'images/seematapakayalu-100-pieces.jpg',
    description: '100 pieces box of traditional crisp sound ground crackers.',
    rating: 4.7
  },
  {
    id: 'lakshmi-big',
    name: 'Lakshmi Big',
    teluguName: 'లక్ష్మీ బాంబులు పెద్దవి',
    pieces: '5 pieces',
    category: 'sound',
    price: 50,
    image: 'images/lakshmi-big.jpg',
    description: 'Heavy explosive sound with traditional green foil Lakshmi branding.',
    rating: 4.9,
    badge: 'Loud Blast'
  },
  {
    id: 'lakshmi-small',
    name: 'Lakshmi Small',
    teluguName: 'లక్ష్మీ బాంబులు చిన్నవి',
    pieces: '5 pieces',
    category: 'sound',
    price: 30,
    image: 'images/laxmi-bombs.jpg',
    description: 'Clear crisp sound blast, great value pack of 5 bombs.',
    rating: 4.7
  },
  {
    id: 'vankayalu-deluxe',
    name: 'Vankayalu Deluxe',
    teluguName: 'వంకాయలు డీలక్స్',
    pieces: '10 pieces',
    category: 'sound',
    price: 450,
    originalPrice: 563,
    discount: '20% OFF',
    image: 'images/vankayalu-deluxe.jpg',
    description: 'Extremely high decibel sound cracker in legendary brinjal bomb design.',
    rating: 5.0,
    badge: 'Super Thunder'
  },
  {
    id: 'vankayalu-big',
    name: 'Vankayalu Big',
    teluguName: 'వంకాయలు పెద్దవి',
    pieces: '10 pieces',
    category: 'sound',
    price: 300,
    originalPrice: 375,
    discount: '20% OFF',
    image: 'images/vankayalu-big.jpg',
    description: 'Solid resounding bass blast loved by cracker connoisseurs.',
    rating: 4.8
  },
  {
    id: 'vankayalu-small',
    name: 'Vankayalu Small',
    teluguName: 'వంకాయలు చిన్నవి',
    pieces: '10 pieces',
    category: 'sound',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/vankayalu-small.jpg',
    description: 'Compact vankayalu bombs with strong sound and bright colour burst.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'flower-outs',
    name: 'Flower Outs',
    teluguName: 'ఫ్లవర్ అవుట్స్',
    pieces: '5 pieces',
    category: 'sound',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/flower-outs.jpg',
    description: 'Five piece flower out pack producing big colourful flowers with heavy sound.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: 'wala',
    name: 'Wala',
    teluguName: 'వాలా',
    pieces: '1 packet',
    category: 'sound',
    price: 30,
    image: 'images/wala.jpg',
    description: 'Short rhythm sequence of 28 crisp celebratory pops.',
    rating: 4.6
  },
  {
    id: '100-wala',
    name: '100 Wala',
    teluguName: '100 వాలా',
    pieces: '1 packet',
    category: 'sound',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/100-wala.png',
    description: '100 continuous rapid red firecracker string bursting with vibrant energy.',
    rating: 4.8
  },
  {
    id: '200-wala',
    name: '200 Wala',
    teluguName: '200 వాలా',
    pieces: '1 packet',
    category: 'sound',
    price: 150,
    originalPrice: 188,
    discount: '20% OFF',
    image: 'images/200-wala.jpg',
    description: 'Two hundred wala long garland string for a continuous crackling show.',
    rating: 4.5,
    needsPhoto: true
  },
  {
    id: '1000-wala-1k',
    name: '1000 Wala (1K)',
    teluguName: '1000 వాలా (1కె)',
    pieces: '1 packet',
    category: 'sound',
    price: 350,
    originalPrice: 438,
    discount: '20% OFF',
    image: 'images/1000-wala-1k.jpg',
    description: 'Massive 1000 cracker garland for grand inaugurations, poojas & Diwali night.',
    rating: 5.0,
    badge: 'Grand Sound'
  },
  {
    id: '2000-wala-2k',
    name: '2000 Wala (2K)',
    teluguName: '2000 వాలా (2కె)',
    pieces: '1 packet',
    category: 'sound',
    price: 600,
    originalPrice: 750,
    discount: '20% OFF',
    image: 'images/2000-wala-2k.png',
    description: 'Unstoppable 2000-shot garland filling the festival night with booming beats.',
    rating: 5.0,
    badge: 'Jumbo Garland'
  },
  // ------------------------------------------------------------------
  // Sky Shots & Rockets
  // ------------------------------------------------------------------
  {
    id: 'rockets-big',
    name: 'Rockets Big',
    teluguName: 'రాకెట్లు పెద్దవి',
    pieces: '10 pieces',
    category: 'shots',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/rockets-10-pieces.jpg',
    description: 'Sky piercing rockets bursting into brilliant stars and crackles in mid-air.',
    rating: 4.8
  },
  {
    id: 'rockets-small',
    name: 'Rockets Small',
    teluguName: 'రాకెట్లు చిన్నవి',
    pieces: '10 pieces',
    category: 'shots',
    price: 150,
    originalPrice: 188,
    discount: '20% OFF',
    image: 'images/rockets-small.jpg',
    description: 'High flying whistling rockets bursting into sparkling multi-colored umbrellas.',
    rating: 4.9,
    badge: 'High Flyer'
  },
  {
    id: '1-shot',
    name: '1 Shot',
    teluguName: '1 షాట్',
    pieces: '1 piece',
    category: 'shots',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/1-shot.jpg',
    description: 'Launches high into the sky and detonates with a thunderous golden burst.',
    rating: 4.8
  },
  {
    id: '12-shots',
    name: '12 Shots',
    teluguName: '12 షాట్స్',
    pieces: '1 box',
    category: 'shots',
    price: 200,
    originalPrice: 250,
    discount: '20% OFF',
    image: 'images/12-shots.jpg',
    description: '12 synchronized aerial shots painting the night sky with glittering peonies.',
    rating: 4.8
  },
  {
    id: '15-shots',
    name: '15 Shots',
    teluguName: '15 షాట్స్',
    pieces: '1 box',
    category: 'shots',
    price: 400,
    originalPrice: 500,
    discount: '20% OFF',
    image: 'images/15-shots.png',
    description: '15 rapid aerial bursts with crackling palm trees and strobe willows.',
    rating: 4.9
  },
  {
    id: '30-shots',
    name: '30 Shots',
    teluguName: '30 షాట్స్',
    pieces: '1 box',
    category: 'shots',
    price: 700,
    originalPrice: 875,
    discount: '20% OFF',
    image: 'images/30-shots.jpg',
    description: 'Professional grade continuous 30-shot aerial fireworks show with cracking tails.',
    rating: 5.0,
    badge: 'Pro Display'
  },
  // ------------------------------------------------------------------
  // Family Packs
  // ------------------------------------------------------------------
  {
    id: 'family-pack-deluxe',
    name: 'Mega Family Pack (Diwali Dhamaka)',
    teluguName: 'శ్రీ అయ్యప్ప మెగా ఫ్యామిలీ ప్యాక్',
    pieces: '30 Items',
    category: 'special-packs',
    price: 3199,
    originalPrice: 3999,
    discount: '20% OFF',
    image: 'images/family-pack-deluxe.jpg',
    description: 'Curated Diwali dhamaka pack with sparklers, flower pots, chakkars, shots, sound crackers and rockets — every item listed below with its pack quantity.',
    contents: [
      { name: '7cm Sparklers', qty: 2 },
      { name: '7cm Electrical Sparklers', qty: 2 },
      { name: '15cm Red Colour Sparklers', qty: 2 },
      { name: '15cm Green Colour Sparklers', qty: 2 },
      { name: '30cm Sparklers', qty: 2 },
      { name: 'Chichubudi Big Box', qty: 1 },
      { name: 'Chichubudi Medium Box', qty: 1 },
      { name: '100 Wala', qty: 2 },
      { name: 'Colour Match Box', qty: 1 },
      { name: 'Pamubilalu Box', qty: 1 },
      { name: 'Bhuchakralu Big Box', qty: 1 },
      { name: '12 Shots', qty: 1 },
      { name: 'Lakshmi Bombulu Big', qty: 1 },
      { name: 'Ganga Jamuna (Flower Outs)', qty: 1 },
      { name: '28 Wala', qty: 4 },
      { name: '1000 Wala Box', qty: 1 },
      { name: '1 Shot', qty: 2 },
      { name: 'Threads (Tadulu) Big', qty: 1 },
      { name: 'Threads (Tadulu) Small', qty: 1 },
      { name: 'Vennamudalu Box', qty: 2 },
      { name: 'Chitpatlu Box', qty: 2 },
      { name: 'Rockets Box Big', qty: 1 },
      { name: 'Rockets Box Small', qty: 1 },
      { name: 'Smoke (Beedi Bombs)', qty: 4 },
      { name: 'Sematapakayalu Packets', qty: 2 },
      { name: 'Pop Ups (Nelatapakayalu)', qty: 5 },
      { name: 'Bullets', qty: 1 },
      { name: 'Pencils Box', qty: 1 },
      { name: 'Vankaya Bombulu Small', qty: 1 },
      { name: 'Pitta Bombs', qty: 4 }
    ],
    rating: 4.9,
    badge: 'Best Seller'
  }
];
