// Sri Ayyappa Crackers - Complete Product Catalog
const CONTACTS = [
  { id: 'gowtham', name: 'Gowtham', phone: '9640499753', displayPhone: '+91 96404 99753', role: 'Main Orders & Support', isDefault: true },
  { id: 'guruswami', name: 'Guruswami', phone: '9573047342', displayPhone: '+91 95730 47342', role: 'Sales & Bulk Booking' }
];

const CATEGORIES = [
  { id: 'all', name: 'All Fireworks', icon: '✨' },
  { id: 'sparklers', name: 'Sparklers (కాకరపువ్వులు)', icon: '🌟' },
  { id: 'ground', name: 'Ground Items (భూచక్రాలు & చిచ్చుబుడ్లు)', icon: '🌀' },
  { id: 'special-packs', name: 'Special Family Packs (ఫ్యామిలీ ప్యాక్)', icon: '🎁' },
  { id: 'shots', name: 'Shots Items (షూటింగ్ షాట్స్)', icon: '🚀' },
  { id: 'sound', name: 'Outs Big Sounds (వాలా & లక్ష్మీ బాంబులు)', icon: '💥' },
  { id: 'aerial', name: 'Aerial Items (ఆకాశ తారలు)', icon: '🎆' }
];

const PRODUCTS = [
  // Sparklers
  {
    id: 'kakarapulu-7cm',
    name: 'Kakarapulu 7cm',
    teluguName: 'కాకరపువ్వులు 7 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 15,
    originalPrice: 19,
    discount: '20% OFF',
    image: 'images/kakarapulu-7cm10-pieces.jpg',
    description: 'Bright golden and silver sparks suitable for kids and quick celebrations.',
    rating: 4.8,
    badge: 'Best Seller'
  },
  {
    id: 'kakarapulu-15cm-colour',
    name: 'Kakarapulu 15cm Colour Green/Red',
    teluguName: 'కలర్ కాకరపువ్వులు 15 సెం.మీ',
    pieces: '10 pieces',
    category: 'sparklers',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/kakarapulu-15cm-colour-greenred-10-pieces.jpg',
    description: 'Vibrant dual-color green and red glittering sparks with long burning duration.',
    rating: 4.9,
    badge: 'Popular'
  },
  {
    id: 'kakarapulu-30cm-plain',
    name: 'Kakarapulu 30cm Plain',
    teluguName: 'కాకరపువ్వులు 30 సెం.మీ ప్లెయిన్',
    pieces: '5 pieces',
    category: 'sparklers',
    price: 50,
    originalPrice: 65,
    discount: '20% OFF',
    image: 'images/kakarapulu-30cm-colour-5-pieces.jpg',
    description: 'Extra long traditional sparkler giving steady bright fireworks illumination.',
    rating: 4.7
  },
  {
    id: 'kakarapulu-30cm-colour',
    name: 'Kakarapulu 30cm Colour',
    teluguName: 'రంగుల కాకరపువ్వులు 30 సెం.మీ',
    pieces: '5 pieces',
    category: 'sparklers',
    price: 70,
    originalPrice: 88,
    discount: '20% OFF',
    image: 'images/30-shots.jpg',
    description: '30cm giant multicolored sparkles, super vibrant celebration special.',
    rating: 4.9
  },
  {
    id: 'pencils',
    name: 'Pencils Sparklers',
    teluguName: 'పెన్సిల్స్ మతాబులు',
    pieces: '10 Pieces',
    category: 'sparklers',
    price: 140,
    originalPrice: 175,
    discount: '20% OFF',
    image: 'images/pencil.jpg',
    description: 'Handheld pencil sticks producing continuous bursts of bright colorful stars.',
    rating: 4.8,
    badge: 'Kids Favourite'
  },

  // Ground Items
  {
    id: 'nelatapaakayalu-small',
    name: 'Nelatapaakayalu Small',
    teluguName: 'నేలటపాకాయలు చిన్నవి',
    pieces: '30 pieces',
    category: 'ground',
    price: 10,
    originalPrice: 15,
    discount: '33% OFF',
    image: 'images/seema-tapakai.jpg',
    description: 'Classic pop-pop ground snappers safe and enjoyable for children.',
    rating: 4.7
  },
  {
    id: 'chitapatalu',
    name: 'Chitapatalu',
    teluguName: 'చితపటాలు',
    pieces: '10 Pieces',
    category: 'ground',
    price: 60,
    originalPrice: 75,
    discount: '20% OFF',
    image: 'images/chitapatalu-10-pieces.jpg',
    description: 'Playful crackling sounds with golden micro-sparks on the ground.',
    rating: 4.6
  },
  {
    id: 'vennamuddalu',
    name: 'VennaMuddalu',
    teluguName: 'వెన్నముద్దలు',
    pieces: '10 Pieces',
    category: 'ground',
    price: 30,
    originalPrice: 40,
    discount: '20% OFF',
    image: 'images/vennamuddalu-10-pieces.jpg',
    description: 'Smooth glowing ground crackers with soft sound and warm light.',
    rating: 4.5
  },
  {
    id: 'chichubudlu-small',
    name: 'Chichubudlu Small (Flower Pots)',
    teluguName: 'చిచ్చుబుడ్లు చిన్నవి',
    pieces: '10 Pieces',
    category: 'ground',
    price: 250,
    originalPrice: 312,
    discount: '20% OFF',
    image: 'images/chichubudlu-small10-pieces.jpg',
    description: 'Beautiful golden spray fountain that illuminates your courtyard festive style.',
    rating: 4.9,
    badge: 'Top Pick'
  },
  {
    id: 'chichubudlu-big',
    name: 'Chichubudlu Big (Special Flower Pots)',
    teluguName: 'చిచ్చుబుడ్లు పెద్దవి (డీలక్స్)',
    pieces: '10 Pieces',
    category: 'ground',
    price: 300,
    originalPrice: 375,
    discount: '20% OFF',
    image: 'images/chichubudlu-big-10-pieces.jpg',
    description: 'High-height majestic flower fountain with multi-layered shower of sparks.',
    rating: 5.0,
    badge: 'Grand Flower'
  },
  {
    id: 'seematapakayalu-100',
    name: 'Seematapakayalu',
    teluguName: 'సీమటపాకాయలు',
    pieces: '100 Pieces',
    category: 'ground',
    price: 70,
    originalPrice: 88,
    discount: '20% OFF',
    image: 'images/seematapakayalu-100-pieces.jpg',
    description: '100 pieces box of traditional crisp sound ground crackers.',
    rating: 4.7
  },
  {
    id: 'pamubillalu-big',
    name: 'Pamubillalu Big (Black Snake)',
    teluguName: 'పాముబిళ్ళలు పెద్దవి',
    pieces: '10 Pieces',
    category: 'ground',
    price: 140,
    originalPrice: 175,
    discount: '20% OFF',
    image: 'images/pamubillalu-big10-pieces.jpg',
    description: 'Jumbo size expanding smoke serpent pellets beloved across generations.',
    rating: 4.6
  },
  {
    id: 'pamubillalu-small',
    name: 'Pamubillalu Small',
    teluguName: 'పాముబిళ్ళలు చిన్నవి',
    pieces: '10 Pieces',
    category: 'ground',
    price: 5,
    originalPrice: 8,
    discount: '37% OFF',
    image: 'images/pamubillalu-small-10-pieces.jpg',
    description: 'Pocket-friendly black snake pellets for fun Diwali games.',
    rating: 4.4
  },
  {
    id: 'kunda-bombulu',
    name: 'Kunda Bombulu',
    teluguName: 'కుండ బాంబులు (మట్కా బాంబ్)',
    pieces: '1 Piece',
    category: 'ground',
    price: 70,
    originalPrice: 88,
    discount: '20% OFF',
    image: 'images/kunda-bombulu-1-pieces.jpg',
    description: 'Pot shaped cracker generating powerful bass resonance and colorful flare.',
    rating: 4.8
  },
  {
    id: 'bhuchakaram-big',
    name: 'Bhuchakaram Big (Ground Spinner)',
    teluguName: 'భూచక్రం పెద్దది',
    pieces: '10 Pieces',
    category: 'ground',
    price: 160,
    originalPrice: 200,
    discount: '20% OFF',
    image: 'images/bhuchakaram-big.jpg',
    description: 'High-speed spinning wheel producing a huge ring of dynamic sparks.',
    rating: 4.9,
    badge: 'Popular'
  },
  {
    id: 'bhuchakaram-small',
    name: 'Bhuchakaram Small',
    teluguName: 'భూచక్రం చిన్నది',
    pieces: '10 Pieces',
    category: 'ground',
    price: 120,
    originalPrice: 150,
    discount: '20% OFF',
    image: 'images/bhoo-chakram.jpg',
    description: 'Classic ground chakkar with smooth continuous spin and glittering circle.',
    rating: 4.7
  },

  // Special Packs
  {
    id: 'family-pack-deluxe',
    name: 'Mega Family Pack (Diwali Dhamaka)',
    teluguName: 'శ్రీ అయ్యప్ప మెగా ఫ్యామిలీ ప్యాక్',
    pieces: 'All-in-One Deluxe Box',
    category: 'special-packs',
    price: 2000,
    originalPrice: 2500,
    discount: '20% OFF',
    image: 'images/family-pack.jpg',
    description: 'Complete fireworks package for the whole family! Includes Sparklers, Flower Pots, Chakkars, Rockets, Multi-Shots, and Garlands at the best wholesale rate.',
    rating: 5.0,
    badge: 'Mega Saver',
    featured: true
  },
  {
    id: 'family-pack-savari-3500',
    name: 'Grand Family Pack (Festive Offer)',
    teluguName: 'శ్రీ అయ్యప్ప గ్రాండ్ ఫ్యామిలీ ప్యాక్ (20% ఆఫర్)',
    pieces: '28 Items',
    category: 'special-packs',
    price: 2800,
    originalPrice: 3500,
    discount: '20% OFF',
    image: 'images/family-pack.jpg',
    description: 'Complete grand Diwali family combo at the best rate:\n· 30cm Sparkles — 2 packs\n· 30cm Colour Sparkles — 2 packs\n· 15cm Colour Sparkles — 2 packs\n· 7cm Sparkles — 4 packs\n· Threads (Tadulu) — 10 pieces\n· Colour Match Box — 1 pack\n· Chichubudlu Big Box — 1\n· Chichubudlu Small Box — 1\n· Bhuchakralu Big Box — 1\n· Bhuchakralu Small Box — 1\n· Pencils Box — 1\n· Kunda Bombulu — 3 packs\n· Matabulu Packet — 1\n· Vennamudalu Box — 2\n· Chitapatalu Box — 2\n· Pambillalu Box — 4\n· Rockets Box — 1\n· Sematapakayalu Packets — 2\n· Nelatapakayalu (Pop Ups) — 5 packs\n· Lakshmi Bombulu Big — 1\n· Lakshmi Bombulu Small Box — 1\n· Vankaya Bombulu Small & Big Box — 1\n· 28 Wala — 4 packs\n· 100 Wala — 2 packs\n· 1000 Wala Box — 1\n· 1 Shot — 2 packs\n· 12 Shots — 1\n· 2 Sound — 1',
    rating: 5.0,
    badge: 'Grand Combo',
    featured: true
  },

  // Shots Items
  {
    id: 'rockets-pack',
    name: 'Whistling Rockets',
    teluguName: 'రాకెట్లు (10 ముక్కలు)',
    pieces: '10 Pieces',
    category: 'shots',
    price: 140,
    originalPrice: 175,
    discount: '20% OFF',
    image: 'images/rockets.jpg',
    description: 'High flying whistling rockets bursting into sparkling multi-colored umbrellas.',
    rating: 4.9,
    badge: 'High Flyer'
  },
  {
    id: 'one-shot',
    name: '1 Shot Sky Bomb',
    teluguName: '1 షాట్ స్కై బ్లాస్ట్',
    pieces: '1 Piece',
    category: 'shots',
    price: 100,
    originalPrice: 125,
    discount: '20% OFF',
    image: 'images/1shot.jpg',
    description: 'Launches high into the sky and detonates with a thunderous golden burst.',
    rating: 4.8
  },
  {
    id: 'seven-shots',
    name: '7 Shots Sky Thunder',
    teluguName: '7 షాట్స్ స్కై థండర్',
    pieces: '5 pieces',
    category: 'shots',
    price: 180,
    originalPrice: 225,
    discount: '20% OFF',
    image: 'images/7shots.jpg',
    description: '5 pipes each delivering 7 rapid sky-breaking colorful explosions.',
    rating: 4.9
  },
  {
    id: 'twelve-shots',
    name: '12 Shots Spectacular Sky',
    teluguName: '12 షాట్స్ మల్టీ కలర్',
    pieces: '1 Box',
    category: 'shots',
    price: 250,
    originalPrice: 312,
    discount: '20% OFF',
    image: 'images/12-shots.jpg',
    description: '12 synchronized aerial shots painting the night sky with glittering peonies.',
    rating: 4.8
  },
  {
    id: 'fifteen-shots',
    name: '15 Shots Deluxe Aerial',
    teluguName: '15 షాట్స్ డీలక్స్ ఆకాశబాణం',
    pieces: '1 Box',
    category: 'shots',
    price: 300,
    originalPrice: 375,
    discount: '20% OFF',
    image: 'images/15-shots.jpg',
    description: '15 rapid aerial bursts with crackling palm trees and strobe willows.',
    rating: 4.9
  },
  {
    id: 'thirty-shots',
    name: '30 Shots Grand Celebration Show',
    teluguName: '30 షాట్స్ గ్రాండ్ సెలెబ్రేషన్',
    pieces: '1 Box',
    category: 'shots',
    price: 600,
    originalPrice: 750,
    discount: '20% OFF',
    image: 'images/30-shots.jpg',
    description: 'Professional grade continuous 30-shot aerial fireworks show with cracking tails.',
    rating: 5.0,
    badge: 'Pro Display'
  },

  // Outs Big Sounds
  {
    id: '28-wala',
    name: '28 Wala Cracker String',
    teluguName: '28 వాలా సరాలు',
    pieces: '1 Packet',
    category: 'sound',
    price: 20,
    originalPrice: 25,
    discount: '20% OFF',
    image: 'images/28-wala-1-packet.jpg',
    description: 'Short rhythm sequence of 28 crisp celebratory pops.',
    rating: 4.6
  },
  {
    id: '100-wala',
    name: '100 Wala Garland',
    teluguName: '100 వాలా లడి',
    pieces: '1 packet',
    category: 'sound',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/100-wala.jpg',
    description: '100 continuous rapid red firecracker string bursting with vibrant energy.',
    rating: 4.8
  },
  {
    id: '1000-wala',
    name: '1000 Wala Mega Garland',
    teluguName: '1000 వాలా మెగా లడి',
    pieces: '1 Packet',
    category: 'sound',
    price: 350,
    originalPrice: 437,
    discount: '20% OFF',
    image: 'images/1000-wala.jpg',
    description: 'Massive 1000 cracker garland for grand inaugurations, poojas & Diwali night.',
    rating: 5.0,
    badge: 'Grand Sound'
  },
  {
    id: '2000-wala',
    name: '2000 Wala Royal Garland',
    teluguName: '2000 వాలా రాయల్ లడి',
    pieces: '1 Packet',
    category: 'sound',
    price: 600,
    originalPrice: 750,
    discount: '20% OFF',
    image: 'images/2000-wala.jpg',
    description: 'Unstoppable 2000-shot garland filling the festival night with booming beats.',
    rating: 5.0,
    badge: 'Jumbo Garland'
  },
  {
    id: 'laxmi-big',
    name: 'Laxmi Big Bomb',
    teluguName: 'లక్ష్మీ బాంబులు పెద్దవి',
    pieces: '5 Pieces',
    category: 'sound',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/laxmi-big-5-pieces.jpg',
    description: 'Heavy explosive sound with traditional green foil Lakshmi branding.',
    rating: 4.9,
    badge: 'Loud Blast'
  },
  {
    id: 'laxmi-medium',
    name: 'Laxmi Medium Bomb',
    teluguName: 'లక్ష్మీ బాంబులు మీడియం',
    pieces: '5 Pieces',
    category: 'sound',
    price: 70,
    originalPrice: 88,
    discount: '20% OFF',
    image: 'images/laxmi-medium-5-pieces.jpg',
    description: 'Medium sound intensity high quality authentic Sivakasi Lakshmi bomb.',
    rating: 4.8
  },
  {
    id: 'laxmi-small',
    name: 'Lakshmi Small Bomb',
    teluguName: 'లక్ష్మీ బాంబులు చిన్నవి',
    pieces: '5 Pieces',
    category: 'sound',
    price: 60,
    originalPrice: 75,
    discount: '20% OFF',
    image: 'images/laxmi-bombs.jpg',
    description: 'Clear crisp sound blast, great value pack of 5 bombs.',
    rating: 4.7
  },
  {
    id: 'two-sound',
    name: '2 Sound Bomb (Double Blast)',
    teluguName: '2 సౌండ్ డబుల్ ధమాకా',
    pieces: '5 Pieces',
    category: 'sound',
    price: 80,
    originalPrice: 100,
    discount: '20% OFF',
    image: 'images/2-sound-5-pieces.jpg',
    description: 'Exciting dual explosion cracker: first bang followed immediately by second!',
    rating: 4.9,
    badge: 'Double Blast'
  },
  {
    id: 'vankaya-ultra-deluxe',
    name: 'Vankaya Ultra Deluxe (Brinjal Bomb)',
    teluguName: 'వంకాయ ఆల్ట్రా డీలక్స్ బాంబులు',
    pieces: '10 pieces',
    category: 'sound',
    price: 350,
    originalPrice: 437,
    discount: '20% OFF',
    image: 'images/vinkaya-big.jpg',
    description: 'Extremely high decibel sound cracker in legendary brinjal bomb design.',
    rating: 5.0,
    badge: 'Super Thunder'
  },
  {
    id: 'vankaya-medium',
    name: 'Vankaya Medium Bomb',
    teluguName: 'వంకాయ మీడియం బాంబులు',
    pieces: '10 Pieces',
    category: 'sound',
    price: 300,
    originalPrice: 375,
    discount: '20% OFF',
    image: 'images/vankaya-medium-10-pieces.jpg',
    description: 'Solid resounding bass blast loved by cracker connoisseurs.',
    rating: 4.8
  },

  // Aerial Items
  {
    id: 'rockets-deluxe-10',
    name: 'Colour Sky Rockets Deluxe',
    teluguName: 'కలర్ స్కై రాకెట్స్ డీలక్స్',
    pieces: '10 Pieces',
    category: 'aerial',
    price: 120,
    originalPrice: 150,
    discount: '20% OFF',
    image: 'images/rockets-10-pieces.jpg',
    description: 'Sky piercing rockets bursting into brilliant stars and crackles in mid-air.',
    rating: 4.8
  },
  {
    id: 'one-shot-aerial',
    name: '1 Shot Colour Ball Aerial',
    teluguName: '1 షాట్ కలర్ బాల్ ఏరియల్',
    pieces: '1 Piece',
    category: 'aerial',
    price: 100,
    originalPrice: 125,
    discount: '20% OFF',
    image: 'images/1-shot.jpg',
    description: 'High soaring single cannon shot bursting into emerald green & ruby red stars.',
    rating: 4.9
  }
];
